const DOMElements = {
  importLocalBtn: document.getElementById('import-local-btn'),
  importServerBtn: document.getElementById('import-server-btn'),
  clearDbBtn: document.getElementById('clear-db-btn'),
  logModal: document.getElementById('log-modal'),
  logList: document.getElementById('log-list'),
  closeLogModalBtn: document.getElementById('close-log-modal-btn'),
  fileImporter: document.getElementById('file-importer'),
  inputText: document.getElementById('input-text'),
  translateBtn: document.getElementById('translate-btn'),
  clearBtn: document.getElementById('clear-btn'),
  copyBtn: document.getElementById('copy-btn'),
  exportBtn: document.getElementById('export-btn'),
  outputPanel: document.getElementById('output-panel'),

  nameListTextarea: document.getElementById('name-list-textarea'),
  nameListSaveBtn: document.getElementById('name-list-save'),
  nameListDeleteBtn: document.getElementById('name-list-delete'),
  nameListExportBtn: document.getElementById('name-list-export'),
  nameListImportBtn: document.getElementById('name-list-import'),
  nameListFileInput: document.getElementById('name-list-file-input'),

  loader: document.getElementById('loader'),
  loaderText: document.getElementById('loader-text'),
  modeToggle: document.getElementById('mode-toggle'),
  saveTextToggle: document.getElementById('save-text-toggle'),
  increaseFontBtn: document.getElementById('increase-font-btn'),
  decreaseFontBtn: document.getElementById('decrease-font-btn'),
  fontSizeLabel: document.getElementById('font-size-label'),

  editModal: document.getElementById('edit-modal'),
  closeEditModalBtn: document.getElementById('close-edit-modal-btn'),
  editModalLockBtn: document.getElementById('edit-modal-lock-btn'),
  originalWordInput: document.getElementById('original-word-input'),
  customMeaningInput: document.getElementById('custom-meaning'),
  addToNameListBtn: document.getElementById('add-to-name-list-btn'),
  addTempBtn: document.getElementById('add-temp-btn'),
  expandLeftBtn: document.getElementById('expand-left-btn'),
  expandRightBtn: document.getElementById('expand-right-btn'),
  vietphraseInput: document.getElementById('vietphrase-input'),
  vietphraseToggleBtn: document.getElementById('vietphrase-toggle-btn'),
  vietphraseOptionsContainer: document.getElementById('vietphrase-options-container'),

  quickEditPanel: document.getElementById('quick-edit-panel'),
  qExpandLeftBtn: document.getElementById('q-expand-left-btn'),
  qExpandRightBtn: document.getElementById('q-expand-right-btn'),
  qAddNameBtn: document.getElementById('q-add-name-btn'),
  qInputZw: document.getElementById('q-input-zw'),
  qInputHv: document.getElementById('q-input-hv'),
  qInputHV: document.getElementById('q-input-HV'),
  qInputVp: document.getElementById('q-input-Vp'),
  qInputTc: document.getElementById('q-input-tc'),
  qSearchBtn: document.getElementById('q-search-btn'),
  qCopyBtn: document.getElementById('q-copy-btn'),
  editModalDeleteBtn: document.getElementById('edit-modal-delete-btn'),
  qDeleteBtn: document.getElementById('q-delete-btn'),
  qLockBtn: document.getElementById('q-lock-btn'),
  qCloseBtn: document.getElementById('q-close-btn'),
};

export default DOMElements;